%% data 불러오기
clear all
clc

Cumulative_Gas = xlsread('VVS_ALL.xlsx','Cumulative');
%% Graph
Year = 0:size(Cumulative_Gas,1); % load year
CumGas(size(Cumulative_Gas, 1)+1,size(Cumulative_Gas, 2)) = 0;
% CumGas
CumGas(2:size(CumGas,1),:) = Cumulative_Gas; % load Cumulative Gas Production History
CumGas = CumGas * 1e-6;
% h = figure;
% plot(Year,CumGas,'Color','#bebebe')
% hold on
% 
% plot(Year,CumGas(:,size(CumGas,2)),'LineWidth',1.8,'Color','#FF0000')
% xlabel('Time (Year)','FontWeight','bold')
% ylabel('Cumulative Gas Production (MMscf)','FontWeight','bold')
% saveas(h,sprintf('Cumulative Gas Production(Exp).png'));
% close all

Cumulative_Gas_ANN = Proxy_Val(xlsread('VVS_ALL.xlsx','Parameter'));
% Predict
Cumulative_Gas_ANN = xlsread('VVS_ALL(ANN)');
CumGas_ANN(size(Cumulative_Gas_ANN, 1)+1,size(Cumulative_Gas_ANN, 2)) = 0;
% CumGas
CumGas_ANN(2:size(CumGas_ANN,1),:) = Cumulative_Gas_ANN; % load Cumulative Gas Production History

h = figure;
% h.Position = [870.3333 643.6667 695.3333 420.0000];
plot(Year,CumGas_ANN,'Color','#bebebe')
legend('Total Scenarios')
hold on

scatter(Year,CumGas_ANN(:,size(CumGas_ANN,2)),...
'LineWidth',1.5,'MarkerEdgeColor','#FF0000')
xlabel('Time (Year)','FontWeight','bold')
ylabel('Cumulative Gas Production (MMscf)','FontWeight','bold')
legend('Total Scenarios',...
    '','','','','','','','','','',...
    '','','','','','','','','','',...
    '','','','','','','','','','',...
    '','','','','','','','','','',...
    '','','','','','','','','','',...
    '','','','','','','','','','',...
    '','','','','','','','','','',...
    '','','','','','','','','','',...
    '','','','','','','','','','',...
    '','','','','','','','','','',...
    '','','','','','','','','','',...
    '','','','','','','','','','',...
    '','','','','','','','','','',...
    '','','','','','','','','','',...
    '','','','','','','','','','',...
    '','','','','','','','','','',...
    '','','','','','','','','','',...
    '','','','','','','','','','',...
    '','','','','','','','','','',...
    '','','','','','','','','','',...
    '','','','','','','','','','',...
    '','','','','','','','','','',...
    '','','','','','','','','','',...
    '','','','','','','','','','',...
    '','','','','','','','','','',...
    '','','','','','','','','','',...
    '','','','','','','','','','',...
    '','','','','Base case Scenario',...
    'FontWeight','bold',...
    'Location','northwest')
saveas(h,sprintf('Cumulative Gas Production(ANN).png'));
close all

%% Versus